const express = require('express') 
const exphbs = require('express-handlebars')
const app = express()
const produtosRoutes = require('./routes/produtosRoutes')
app.engine('handlebars', exphbs.engine())
app.set('view engine', 'handlebars')
app.use(express.urlencoded({extended: true}),)
app.use(express.json())
app.use(express.static('public'))
app.use('/produtos', produtosRoutes)
app.listen(3000)